-> Movimento e Time
@startuml

skinparam linetype ortho

!include src/frameworkJogoDeTabuleiro/model/multiton/movimento/estruturaMovimento.puml
!include src/frameworkJogoDeTabuleiro/model/multiton/time/estruturaTime.puml

class Jogador {
    - String nome;
    - Time time;
    - List<Movimento> movimentos;
    - Movimento movimento;
    + realizarMovimento(movimento: Movimento , time: Time)
    + getMovimentos(): List<Movimento>
}
Jogador *-- Time : pretence a
Jogador --> Movimento : realiza
@enduml


