@startuml

skinparam line ortho

class Posicao {
    - int linha
    - int coluna
    --
    + Posicao(int linha, int coluna)
    + int getLinha()
    + void setLinha(int linha)
    + int getColuna()
    + void setColuna(int coluna)
    + boolean equals(Object obj)
    + int hashCode()
    + String toString()
}
@enduml
