@startuml 
skinparam linetype ortho

!include src/main/java/br/com/frameworkPpr/xadrez/board/tabuleiro/singletonEProxySecurity/puml/singleton/estruturaTabuleiro.puml

class GerarJogo {
    - FrameworkJogoDeTabuleiro jogo;
    + criarJogo(String nomeJogo) : Tabuleiro
    + iniciarJogo() : void
}

GerarJogo --> Tabuleiro : cria

note right of Tabuleiro
O padrão Singleton garante que
apenas uma instância do jogo seja criada
e compartilhada por todo o sistema.
end note
@enduml