@startuml
skinparam linetype ortho

class VitoriaDerrotaObserver {
    - Tabuleiro tabuleiro
    + VitoriaDerrotaObserver(Tabuleiro tabuleiro)
    + Time verificarVencedor()
    + Tabuleiro getTabuleiro()
    + void setTabuleiro(Tabuleiro tabuleiro)
}

@enduml
