@startuml

skinparam linetype ortho

class Time {
    - String nome;
    + getNome(): String
}

class GerenciadorTimes {
    - Map<String, Time> times;
    + getTime(nome: String): Time
    + adicionarTime(nome: String, time: Time)
}

GerenciadorTimes o-- Time : gerencia

@enduml
