@startuml
skinparam linetype ortho

class Tabuleiro {
    - int linhas
    - int colunas
    - Map<Posicao, Casa> casas
    - Map<Time, Integer> pecasPorTime
    + Tabuleiro(int linhas, int colunas)
    + colocarPeca(Peca peca, Posicao posicao)
    + moverPeca(Posicao origem, Posicao destino)
    + RemoverPeca(Posicao posicao)
    + boolean posicaoValida(int linha, int coluna)
    + boolean posicaoValida(Posicao posicao)
    + Map<Time, Integer> getPecasPorTime()
    + Casa getCasa(Posicao posicao)
}

@enduml
